require:
  - rubocop-rspec
  - rubocop-performance

# Note that the local default.yml is overwritten on CodeClimate with the contents of
# the remote rubocop.yml pulled from GitHub in a codeclimate prepare step.
inherit_from:
  - default.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "db/seeds/**/*"
    - "db/migrate/**/*"
    - "config/initializers/devise.rb"
    - "db/schema.rb"
    - "spec/dummy/db/schema.rb"

RSpec/ExampleLength:
  Max: 20
RSpec/NestedGroups:
  Max: 4
RSpec/MultipleExpectations:
  Max: 4
