default: &default
  adapter: postgresql
  encoding: unicode
  schema_search_path: "renalware,renalware_diaverum,public"
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

default_credentials: &default_credentials
  username: renalware
  password: renalware

development:
  <<: *default
  <<: *default_credentials
  database: renalware_diaverum_development

test:
  <<: *default
  <<: *default_credentials
  database: renalware_diaverum_test

production:
  <<: *default
  url: renalware_diaverum_production
